"""booking id update

Revision ID: 024b5030eee5
Revises: e6d4b77b8226
Create Date: 2023-04-20 17:00:10.972884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024b5030eee5'
down_revision = 'e6d4b77b8226'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
