"""NEW Migrations

Revision ID: 379dbc30583b
Revises: 39704e9725e3
Create Date: 2023-03-12 15:44:10.558467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379dbc30583b'
down_revision = '39704e9725e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employeeId',
    sa.Column('empId', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('empId')
    )
    op.create_index(op.f('ix_employeeId_empId'), 'employeeId', ['empId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employeeId_empId'), table_name='employeeId')
    op.drop_table('employeeId')
    # ### end Alembic commands ###
