"""NEW Migrations

Revision ID: 39704e9725e3
Revises: 92133777cc81
Create Date: 2023-03-12 15:25:53.607949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39704e9725e3'
down_revision = '92133777cc81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employeeId_empId', table_name='employeeId')
    op.drop_table('employeeId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employeeId',
    sa.Column('empId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('empId', name='employeeId_pkey')
    )
    op.create_index('ix_employeeId_empId', 'employeeId', ['empId'], unique=False)
    # ### end Alembic commands ###
