"""bookingapprove  Migrations

Revision ID: 5bbb6172e620
Revises: 8e58e62a644e
Create Date: 2023-03-12 20:39:34.204343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbb6172e620'
down_revision = '8e58e62a644e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_Bookings', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_Bookings', 'reason')
    # ### end Alembic commands ###
