"""booking id update

Revision ID: 5fca786e8f05
Revises: 024b5030eee5
Create Date: 2023-04-20 19:09:54.327980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fca786e8f05'
down_revision = '024b5030eee5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
