"""bookingapprove  Migrations

Revision ID: 8e58e62a644e
Revises: 2376cc56c76b
Create Date: 2023-03-12 20:23:11.075059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e58e62a644e'
down_revision = '2376cc56c76b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_Bookings', sa.Column('remark', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_Bookings', 'remark')
    # ### end Alembic commands ###
