"""NEW Migrations

Revision ID: 92133777cc81
Revises: 
Create Date: 2023-03-12 14:03:28.489514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92133777cc81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('empId', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('empId')
    )
    op.create_index(op.f('ix_accounts_empId'), 'accounts', ['empId'], unique=False)
    op.create_table('employeeId',
    sa.Column('empId', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('empId')
    )
    op.create_index(op.f('ix_employeeId_empId'), 'employeeId', ['empId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employeeId_empId'), table_name='employeeId')
    op.drop_table('employeeId')
    op.drop_index(op.f('ix_accounts_empId'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
