"""email to all id

Revision ID: 94d51aaf039d
Revises: 812065fb9960
Create Date: 2023-04-18 11:41:41.026501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d51aaf039d'
down_revision = '812065fb9960'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employeeId', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employeeId', 'email')
    # ### end Alembic commands ###
