"""models property change  Migrations

Revision ID: d904721fa870
Revises: 8833e59edaa7
Create Date: 2023-03-17 22:28:44.563719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd904721fa870'
down_revision = '8833e59edaa7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_Bookings',
    sa.Column('bookingNumber', sa.String(), nullable=False),
    sa.Column('empId', sa.String(), nullable=True),
    sa.Column('empUsername', sa.String(), nullable=True),
    sa.Column('userDepartment', sa.String(), nullable=True),
    sa.Column('tripDate', sa.String(), nullable=True),
    sa.Column('startLocation', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('startTime', sa.String(), nullable=True),
    sa.Column('endTime', sa.String(), nullable=True),
    sa.Column('vehicleAlloted', sa.String(), nullable=True),
    sa.Column('vehicleNumber', sa.String(), nullable=True),
    sa.Column('tripStatus', sa.Boolean(), nullable=True),
    sa.Column('tripCompleted', sa.Boolean(), nullable=True),
    sa.Column('tripCanceled', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('bookingNumber')
    )
    op.create_index(op.f('ix_vehicle_Bookings_bookingNumber'), 'vehicle_Bookings', ['bookingNumber'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_Bookings_bookingNumber'), table_name='vehicle_Bookings')
    op.drop_table('vehicle_Bookings')
    # ### end Alembic commands ###
