"""booking id update

Revision ID: e6d4b77b8226
Revises: 94d51aaf039d
Create Date: 2023-04-20 16:40:46.375643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d4b77b8226'
down_revision = '94d51aaf039d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
