"""changes

Revision ID: e953dd10ea80
Revises: 3c949f141c8f
Create Date: 2023-05-13 20:49:09.528737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e953dd10ea80'
down_revision = '3c949f141c8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('empId', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=600), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('isAuthorized', sa.Boolean(), nullable=True),
    sa.Column('verifyPhoneNumber', sa.Boolean(), nullable=True),
    sa.Column('verifyEmail', sa.Boolean(), nullable=True),
    sa.Column('isOwner', sa.Boolean(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('empId')
    )
    op.create_index(op.f('ix_accounts_empId'), 'accounts', ['empId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_empId'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
