"""empneW Migrations

Revision ID: f5022e6549df
Revises: 379dbc30583b
Create Date: 2023-03-12 15:47:58.904538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5022e6549df'
down_revision = '379dbc30583b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
