"""userfields  Migrations

Revision ID: fafa8d4735fd
Revises: 5bbb6172e620
Create Date: 2023-03-15 11:13:14.332621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fafa8d4735fd'
down_revision = '5bbb6172e620'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('isAuthorized', sa.Boolean(), nullable=True))
    op.add_column('accounts', sa.Column('verifyPhoneNumber', sa.Boolean(), nullable=True))
    op.add_column('accounts', sa.Column('verifyEmail', sa.Boolean(), nullable=True))
    op.add_column('accounts', sa.Column('isOwner', sa.Boolean(), nullable=True))
    op.add_column('accounts', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'isAdmin')
    op.drop_column('accounts', 'isOwner')
    op.drop_column('accounts', 'verifyEmail')
    op.drop_column('accounts', 'verifyPhoneNumber')
    op.drop_column('accounts', 'isAuthorized')
    # ### end Alembic commands ###
